### ISSUE TITLE
memory crash

### ISSUE THREAD

**Issue by nehoox** [tadija/AEXML#128] opened 2017-09-27 12:50 UTC
Hi, 

I just updated my Xcode 8 to Xcode 9 and I have a big problem. when my code executes  : 

` let success = parser.parse()`

in Parser.swift :
 

```
func parse() throws {
        let parser = XMLParser(data: data)
        parser.delegate = self
        
        parser.shouldProcessNamespaces = document.options.parserSettings.shouldProcessNamespaces
        parser.shouldReportNamespacePrefixes = document.options.parserSettings.shouldReportNamespacePrefixes
        parser.shouldResolveExternalEntities = document.options.parserSettings.shouldResolveExternalEntities

        let success = parser.parse()
        
        if !success {
            guard let error = parseError else { throw AEXMLError.parsingFailed }
            throw error
        }
    }
```

my RAM grows up to 3 Go or more ( My record is 45Go ! )

with Xcode 8, I don't have this problem. Can you help me, I'm totally lost ...

Thank's in advance.

**Comment by tadija** [comment] 2017-09-27 12:57
Hi, please check if that's maybe related to Issue #117.

**Comment by nehoox** [comment] 2017-09-27 13:21
that work! thank you very much!

**Comment by nehoox** [comment] 2017-10-16 13:11
hum. It not works completely. 80% of my XML's cause : NSXMLParserErrorDomain erreur : 1.

**Comment by tadija** [comment] 2017-11-25 19:46
I'll close this as duplicate of #117 so we may discuss further there.

**Closed by tadija** 2017-11-25 19:46 UTC
