### ISSUE TITLE
Swift PM: "the package has an unsupported layout"

### ISSUE THREAD

**Issue by dastrobu** [tadija/AEXML#102] opened 2017-01-25 19:04 UTC
When adding AEXML as dependency and run `swift package fetch`, I get:

    error: the package has an unsupported layout, unexpected source file(s) found: <...>/Packages/AEXML-4.0.1/Tests/AEXMLTests.swift
    fix: move the file(s) inside a module

Swift version is: `Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)`

**Comment by Benuuu** [comment] 2017-01-25 20:27
This looks like a duplicate of #95

**Comment by tadija** [comment] 2017-01-25 22:44
Yeah, sorry for waiting, please use this pull request until I make a new version: https://github.com/tadija/AEXML/pull/94

**Comment by kiliankoe** [comment] 2017-01-27 13:07
Would it be possible to merge that PR? That would clear up issues like this. The fact that the tests then (currently) crash doesn't really matter as much in my opinion.

**Comment by tadija** [comment] 2017-01-29 13:40
PR#94 is merged now, thanks for patience.

**Closed by tadija** 2017-01-29 13:40 UTC
