### ISSUE TITLE
Parsing Element within Another element loses the value of the first Element

### ISSUE THREAD

**Issue by willchen** [tadija/AEXML#66] opened 2016-02-19 20:29 UTC
I'm parsing some Shakespeare xml files with AEXML (which is working great for me otherwise BTW) when I experience some problems getting the correct values out of elements from the following xml:

<SPEECH>
    <SPEAKER>SAMPSON</SPEAKER>
    <LINE><STAGEDIR>Aside to GREGORY</STAGEDIR>  Is the law of our side, if I say</LINE>
    <LINE>ay?</LINE>
</SPEECH>

I'm running through the SPEECH element  (speechElement:AEXMLElement)

for child in speechElement.children {
    // when child equals the the first LINE element
    child.value // should equal "Is the law of our side, if I say" but is nil 
}

The LINE element contains the STAGEDIR element correctly, but loses anything after the STAGEDIR.

I've also moved the STAGEDIR element in the line, like so:
<LINE>Is the law of <STAGEDIR>Aside to GREGORY</STAGEDIR>  our side, if I say</LINE>
and " our side, if I say" is lost.

I've worked around it by modifying the xml files, but I wanted to file a bug and let you know.

**Comment by tadija** [comment] 2016-02-20 12:18
That is not a valid XML at first (you can check that on some online XML validator tool), but later after your changes it is valid. So, the AEXML is behaving correctly in this case.

**Comment by willchen** [comment] 2016-02-20 21:01
Sorry, I missed escaping opening the \<STAGEDIR>

Below is the XML that is valid and AEXML was not correctly taking in.

\<SPEECH>
    \<SPEAKER>SAMPSON\</SPEAKER>
    \<LINE>\<STAGEDIR>Aside to GREGORY\</STAGEDIR>  Is the law of our side, if I say\</LINE>
    \<LINE>ay?\</LINE>
\</SPEECH>

**Comment by tadija** [comment] 2016-03-01 08:34
I'm not sure what's the problem, maybe it's related to `NSXMLParser`, maybe some other thing, but let's leave it here and whoever has time to investigate this further, and hopefully fix it, can make a pull request.

**Comment by JimBudet** [comment] 2016-05-19 02:13
I'm seeing the same problem. The following code prints

```swift
let xmlString = "<p>Say <b>Hello</b> World</p>"
let data = xmlString.dataUsingEncoding(NSUTF8StringEncoding)!
let document = try! AEXMLDocument(xmlData: data)
print("\(document.xmlStringCompact)")
```

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><p><b>Hello</b></p>
```

The value of the p element is lost when converting to string.

The problem is with the AEXMLElement.xmlString method. It either prints a child or a value but not both. However the "fix" isn't obvious since this example shows that there can be multiple values for an element and their order (with respect to the children) is significant.

It seems that the Element object needs to keep an ordered list of sub-objects where these sub-objects can be Strings (values) or Elements.

**Comment by franklinyu** [comment] 2016-06-09 09:06
@JimBudet Good point, how about a protocol `ElementLike`/`Elementoid` adopted both by `AEXMLElement` and `String`?

Sometimes user do need only the children who are `AEXMLElement`s. My idea is to having two properties:

```swift
var richChildren: [Elementoid]
var children: [AEXMLElement] {
    richChildren.flatmap { element in
        element as? AEXMLElement
    }
}
```

**Comment by JimBudet** [comment] 2016-06-10 13:09
@franklinyu  If I understand correctly, you're suggesting defining a new property (richChildren) that can contain both values (String) and elements (AEXMLElement). You apparently don't want to declare it as `var richChildren: [AnyObject]` so you want to create a new protocol (Elementoid, for AEXMLElement and String) so that you can declare it as `var richChildren:[Elementoid]` instead.

I think that I understand why you want to add the new protocol (Elementoid) but this protocol doesn't define any behavior (as far as I can tell) and it will clutter the code with empty protocol definitions and class extensions. Because of this, I'm not seeing a "real" advantage over the `AnyObject` approach. But there's not inherit problem with using the protocol either.

I'm curious on your thoughts on how the value, stringValue, boolValue, intValue and doubleValue properties will adapt to this change?

**Comment by franklinyu** [comment] 2016-06-11 01:08
@JimBudet Indeed there is no real advantage to define an empty protocol; it would be enough to simply declare `richChildren` of `AEXMLElement` as `AnyObject` as you stated, and in the document state that it would return an array with elements of only those two classes. It is possible to have some methods in the protocol, for example the `children` and `richChildren` properties:

```swift
extension String: Elementoid {
    var richChildren: [Elementoid] {
        return [];
    }
}
```

However, I admit that it does not help much. So overall, I agree with you.

Speaking of the value properties, I believe that the `value` property should be a calculated one:

```swift
extension AEXMLElement  {
    var value: String? {
        if richChildren.count == 1 && richChildren[0] is String {
            return richChildren[0]
        } else {
            return nil
        }
    }
}
```

and the other value-properties depend on this. Your idea?

I would expect this feature to change the API anyway, so it has to be in version 4.0.0.

**Comment by twstokes** [comment] 2017-04-26 20:00
I've submitted a PR that may help with this: https://github.com/tadija/AEXML/pull/115

**Comment by tadija** [comment] 2017-11-25 19:42
Sorry, I think this goes a bit beyond **simple** XML parser, so I'll close this.

**Closed by tadija** 2017-11-25 19:42 UTC
