### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by milanhorvatovic** [tadija/AEXML#117] opened 2017-06-25 07:02 UTC
Actually, your parser consume a lot of memory in Xcode 9 beta (both 1 and 2) with Swift 4. The problem is with appending string during parsing XML in `Parser.swift`. Appending founded string into `currentValue` allocate new memory, but still hold old one. I'm not sure if it's problem of implementation of calling delegate from XMLParser or they changed something and transfer responsibility of management into implementation of the delegate. Solution is fold processing of `func parser(_ parser: XMLParser, foundCharacters string: String)` into `autoreleasepool` closure.

Does have anybody else that problem with Swift 4?

**Comment by SuperWomble** [comment] 2017-06-25 09:27
Does it only happen in Debug, or in Release build with optimisations on?

**Comment by rasmk** [comment] 2017-10-13 19:16
I do. XCode 9 final. In both debug and release mode.
I have ~1MB binary as B64. During parsing over 12GB was allocated. Then I killed the app.

**Comment by nehoox** [comment] 2017-10-16 14:11
autoreleasepool is ok for small XML. For my part this solution not work for large XML. (NSXMLParserErrorDomain erreur : 1)

**Comment by italankin** [comment] 2017-11-15 06:34
For Swift 3.2 and Xcode Version 9.1 (9B55) the problem is also present.

**Comment by italankin** [comment] 2017-11-15 10:49
I managed to fix issue by changing method body:
```swift
@objc func parser(_ parser: XMLParser, foundCharacters string: String) {
    currentValue.append(string.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines))
    currentElement?.value = currentValue.isEmpty ? nil : currentValue
}
```

**Comment by tadija** [comment] 2017-11-25 19:52
Hi, thanks @milanhorvatovic for reporting this. I'm not really sure why this happens, but I've merged #131 and I'd appreciate if someone can confirm is it fixed now with the latest version 4.2.0?

Also, maybe someone can make PR with a unit test using large sample XML which is causing this bug, then everybody can look for a fix?

**Comment by lucasprates** [comment] 2018-01-22 20:44
This bug took me 2 1/2 days to fix.
I did pretty much the same fix as @italankin did.
I wish I had looked here before adventuring into fixing it. Or updated my API. Damn you, CocoaPods. =D

**Comment by tadija** [comment] 2018-01-22 22:07
Hi @lucasprates, I'm sorry to hear that, but just to confirm, does it mean that fix from #131 is working ok?

**Comment by lucasprates** [comment] 2018-01-22 22:13
Hi @tadija.
I tested with many large files on XCode 9.2, both saving and loading, and it is working smoothly now.
So yes, it is working OK for me on my tests.

**Comment by tadija** [comment] 2018-01-22 22:29
Thank you for confirmation, in that case I'll close this issue, thanks everyone who helped!

**Closed by tadija** 2018-01-22 22:29 UTC
Labels: bug, help wanted
